### ISSUE TITLE
Add URL prefix support

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#104]
I use a single domain to access all components of my monitoring system. To make it possible I use NGINX to route requests for different locations to different destinations. For instance, I have the following configured locations:
```
https://mon.example.com/alerta/
https://mon.example.com/grafana/
https://mon.example.com/prometheus/
https://mon.example.com/alertmanager/
```
All components work fine except Alerta Beta (even old Alerta UI) because it uses absolute URLs in its routing engine.

I suppose that Alerta Beta must work behind a proxy with any URL prefix.

**Comment by satterly** [comment]
Can you provide a minimal nginx config I can use to reproduce this?

**Comment by vykulakov** [comment]
Yes, sure:
```
server {
	listen 443 ssl;
	listen [::]:443 ssl ipv6only=on;

	server_name example.com;

	ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

	include /etc/letsencrypt/options-ssl-nginx.conf;
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

	location / {
		proxy_pass http://127.0.0.1:5000/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /alerta/ {
		alias /opt/alerta/;
	}

	location /alertabeta/ {
		alias /opt/alerta_beta/;
	}

	location /grafana/ {
		proxy_pass http://127.0.0.1:3000/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /prometheus/ {
		auth_pam              "Private area";
		auth_pam_service_name "nginx";

		proxy_pass http://127.0.0.1:9090;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /alertmanager/ {
		auth_pam              "Private area";
		auth_pam_service_name "nginx";

		proxy_pass http://127.0.0.1:9093;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```
And feel free to remove SSL related things.

**Comment by vykulakov** [comment]
Are you sure that this small fix solves the problem?

In my branch I also changed the `/src/services/config.ts` file and anyway I have problems with navigation history now.

**Comment by vykulakov** [comment]
For instance, after opening alerts tabs I see the `/alerts` URL instead of `/alertabeta/alerts` (in my environment)

**Comment by satterly** [comment]
This issue auto-closed when I made that commit that referenced this issue. I'll re-open.

It seems it's only a partial fix. A full fix requires building the app with the path prefix already configured which makes it very difficult to build a docker image that works in all environments.

**publicPath**
>By default, Vue CLI assumes your app will be deployed at the root of a domain, e.g. https://www.my-app.com/. If your app is deployed at a sub-path, you will need to specify that sub-path using this option. For example, if your app is deployed at https://www.foobar.com/my-app/, set publicPath to '/my-app/'.

See https://cli.vuejs.org/config/#publicpath

If you have any suggestions let me know. Thanks.

**Comment by vykulakov** [comment]
The problem still exists.

**Comment by satterly** [comment]
Have you tried the latest commit? Did you set "base_url" in config.json?

**Comment by vykulakov** [comment]
Oh, my mistake. After adding `base_url` I see correct URLs in my browser and after updating my NGINX configuration all works fine.

**Comment by satterly** [comment]
Thanks for verifying. 👍 

FYI, I'm going to rename it to `base_path` because it's a path, not a full URL and also to avoid confusion with the `BASE_URL` server config setting.

**Comment by vykulakov** [comment]
Yeah, good point.

**Comment by satterly** [comment]
Ok. This has been updated.`base_path` must be a "path" only and it should be included in `config.json` for it to be used to dynamically update the Vue route paths.

Thanks for raising this issue. These "real world" deployment issues are exactly the sort of thing that need to be fixed before releasing a production version. 👍

**Comment by vykulakov** [comment]
New version with `base_path` works fine.
