### ISSUE TITLE
re-authentication after refreshing page

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#105]
Alerta Beta always redirects me to the login page after refreshing any current page.

For instance, if I'm exploring alerts on the `/alerts` page and then press the `F5` button to refresh this page I always end up on the login page. It is quite strange because with the previous version of Alerta Web I always stay on the same page without any re-authentication (at least I do not see it).

**Environment**
- OS: Ubuntu 18.04
- API version: 6.8.2
- Deployment: self-hosted
- WSGI environment: dev environment

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab
  Customer views? No

- web UI version: latest master
- CLI version: 6.8.1

**To Reproduce**
1. Go to `/alerts`
2. Refresh the page
3. See login page

**Expected behavior**
I should stay on the same page at the end of reloading without any re-authentication.

**Comment by satterly** [comment]
The previous version uses local storage to keep a local copy of the JWT authentication token. The new version could do something similar, I guess.

I have added a "refresh" button to the new version. Do you use it? Does it not do what you require?

<img width="199" alt="Screenshot 2019-03-26 at 20 57 54" src="https://user-images.githubusercontent.com/615057/55029633-da11b780-500a-11e9-87b9-964cee786909.png">

**Comment by vykulakov** [comment]
I have seen the "refresh" button, but F5 is the simplest and fastest way to refresh the whole page. So the "refresh" button is not so useful for me.

**Comment by vykulakov** [comment]
Awesome!  It works fine now, great job, thanks.
