### ISSUE TITLE
Redirect after authentication does not work

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#106]
After successful authentication with GitLab I stay on the login page. I expect that I should end up on the `/alerts` page, for example, but all look like that redirect on the login page does not work. I  always see the `/login?redirect=%2Falerts` address in the address bar in my browser and the message `Authenticating with GitLab ...` after authentication.

**Environment**
- OS: Ubuntu 18.04
- API version: 6.8.2
- Deployment: self-hosted
- WSGI environment: dev environment

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab
  Customer views? No

- web UI version: latest master
- CLI version: 6.8.1

**To Reproduce**
1. Go to Alerta Beta main page
2. Log in with GitLab
3. See the `Authenticating with GitLab ...` message

**Expected behavior**
Alerta Beta should redirect me to the `/alerts` page (or any previously opened page) after authentication.

**Screenshots**
![Screenshot from 2019-03-26 23-04-17](https://user-images.githubusercontent.com/15159594/55029640-a12e0e80-501b-11e9-85a1-4524e604374f.png)

**Comment by satterly** [comment]
This might have broken following the fix to base path. I'll take a look. Thanks.

**Comment by satterly** [comment]
This works for me using Google ...
![Screen Recording 2019-03-26 at 22 13 45 mov](https://user-images.githubusercontent.com/615057/55034315-7f318d80-5015-11e9-99ae-08423cdbe5e9.gif)

**Comment by satterly** [comment]
You're right. GitLab is broken...

<img width="914" alt="Screenshot 2019-03-26 at 22 28 37" src="https://user-images.githubusercontent.com/615057/55034831-bbb1b900-5016-11e9-9cb8-10e0881836a7.png">

**Comment by satterly** [comment]
This might not be fully fixed, yet. Need to verify.

**Comment by vykulakov** [comment]
It is still not working.

**Comment by vykulakov** [comment]
And I also have problems with logout and redirecting from the root page `/` if I'm already authenticated.

**Comment by satterly** [comment]
Please test again. Thanks.

**Comment by vykulakov** [comment]
Works fine, but now I cannot log out because I always log in immediately after log out.

**Comment by satterly** [comment]
That's because you're still logged in to GitLab. There's no way around that except by logging you out of GitLab when you log out of Alerta but I'd be pretty sure you wouldn't want that.

**Comment by vykulakov** [comment]
Yeah, but log out works correctly in old Alerta and I just expect the same behaviour in Alerta Beta.

**Comment by satterly** [comment]
Actually, no. I could redirect to the logout page. Let me try that.
