### ISSUE TITLE
DevTools console displays 404 error

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#107]
I see the 404 error in the DevTools console after authentication in Alerta Beta. It cannot load the `/user/me/attributes` resource.

**Environment**
- OS: Linux
- API version: 6.8.2
- Deployment: self-hosted
- WSGI environment: dev environment

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab
  Customer views? No

- web UI version: latest master
- CLI version: 6.8.1

**To Reproduce**
1. Open DevTools console
2. Go to Alerta Beta main page
3. Log in with GitLab
4. See the error in the console:

```
/user/me/attributes:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
vue-authenticate.es2015.js:459 Possible Unhandled Promise Rejection: Error: Request failed with status code 404
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.f.(/alertabeta/anonymous function) (https://monitoring.sys.swiftserve.com/alertabeta/js/chunk-vendors.cca74b33.js:29:94124)
```

**Expected behavior**
No error/warning messages

**Comment by satterly** [comment]
Ah, yes. The ability to save user preferences is currently only supported if using Basic Auth. I need to decide whether or not to support this feature for all auth providers from v7.0 onwards or ship the new web UI and add support later.

**Comment by satterly** [comment]
Support added for all auth providers that use OpenID eg. Azure, GitLab, Google, and Keycloak (and possibly Pingfederate, but not tested). User preferences for GitHub and SAML2 not currently supported. See alerta/alerta#904
