### ISSUE TITLE
Event's data on the "data" tab displays incorrectly

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#108]
Event's JSON data on the "data" tab displays in one line without any scroll bar. So I cannot inspect the whole raw data - only some fields of it. Would be better if I could see formatted JSON in multiple lines with indents and so on.

**Environment**
- OS: Ubuntu 18.04
- API version: 6.8.2
- Deployment: self-hosted
- WSGI environment: dev deployment

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab
  Customer views? No

- web UI version: latest master
- CLI version: 6.8.1

**To Reproduce**
1. Go to the event's details page
2. Open the "data" tab
3. See a small piece of data

**Expected behavior**
Possibility to see all raw data

**Screenshots**
![Screenshot from 2019-03-26 23-26-46](https://user-images.githubusercontent.com/15159594/55030998-ab9dd780-501e-11e9-9f5d-1f94ddfce88f.png)

**Comment by satterly** [comment]
In the current version if the line is too long the window becomes scrollable. So either reimplement that or make long lines wrap.

**Comment by satterly** [comment]
<img width="878" alt="Screenshot 2019-03-26 at 23 20 54" src="https://user-images.githubusercontent.com/615057/55037368-d50a3380-501d-11e9-917c-6dfd106cf775.png">

**Comment by vykulakov** [comment]
Thanks, it works now.
