### ISSUE TITLE
Preserve alerts table state between page reloadings

### ISSUE THREAD

**Issue by vykulakov** [alerta/beta.alerta.io#109]
It is not so convenient when the state of the alerts table resetting after refreshing/reopening the related page. It even happens after returning to the alerts page from the details page. Under the table state I mean sort order, current filter setting and so on.

So it will be good if we save the table state in local storage and will use it after returning on the `/alerts` page.

**Comment by satterly** [comment]
I can see that sort order resets to the default but current filter settings should already save between pages and view details and back, but not F5 refreshes (see #88).

For me, the following settings are preserved when switching between alerts and other pages, and alerts and the alert details page ...

<img width="298" alt="Screenshot 2019-03-26 at 21 50 43" src="https://user-images.githubusercontent.com/615057/55032545-5f986600-5011-11e9-8598-c4beea9c737e.png">

Can you confirm that filter settings are not saved and if not whether there are any errors in the javascript console?

**Comment by vykulakov** [comment]
Yeah, I must describe problems more accurately.

The filter settings are saved when I'm back from other pages and when I use the refresh button. But refreshing through F5 resets all settings.

**Comment by vykulakov** [comment]
Looks like F5 still resets filter/table settings.

**Comment by satterly** [comment]
I'm still working on that part. It is not a small change.
